server:
  port: 9001
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/henuuDigPlayer/config-repository
          search-paths: config                             # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 2118089226@qq.com                                            # git仓库的账号
          password: *****************
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: lindj
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.84:8000/eureka/
management:
  security:
     enabled: false
